# Generated by Django 4.1.7 on 2023-03-05 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("owner", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("O", "Open"), ("P", "Private")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CourseTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("course_position", models.IntegerField()),
                (
                    "course_id",
                    models.ForeignKey(
                        default=-1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicMaterials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_path", models.CharField(max_length=500)),
                (
                    "course_topic_id",
                    models.ForeignKey(
                        default=-1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="course.coursetopic",
                    ),
                ),
            ],
        ),
    ]
