# Generated by Django 4.1.7 on 2023-03-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="course",
            name="summary",
            field=models.TextField(default=""),
        ),
    ]
